version: 2

# project.dataset.table

# dbt schema = bigquery dataset
# dbt identifier = bigquery table

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null          
          - name: shiping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/transporter
      - name: int_sales_margin
        description: margin calculation per order line / product sale
        columns:
          - name: margin
            description: Margin = Revenue - Purchase_cost
          - name: Purchase_Cost
            description: Purchase_cost = Quantity * Purchase_price
      - name: int_orders_margin
        description: margin calculation per order
        columns:
          - name: order_id
            description: primary key
          - name: margin
            description: Margin = Revenue - Purchase_cost
          - name: Purchase_cost
            description: Purchase_cost = Quantity * Purchase_price
          - name: date_date
            description: date of the order
          - name: revenue
            description: sum of revenue per order
          - name: quantity
            description: sum of quantity per order
      - name: int_orders_operational
        description: operationalmargin calculation per order
        columns:
          - name: operational_margin
            description: Operational margin = margin + shipping fee - log_cost - ship_cost
      - name: finance_days
        description: finance calculation per days
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords marketing campaign
        column:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: Adwords    
          - name: campaign_key
            description: key of campaign
          - name: campaign_name
            description: name of campaign
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: bing 
        identifier: raw_gz_bing
        description: bing marketing campaign
        column:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: bing   
          - name: campaign_key
            description: key of campaign
          - name: campaign_name
            description: name of campaign
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks   
      - name: criteo
        identifier: raw_gz_criteo
        description: bing marketing campaign
        column:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: criteo
          - name: campaign_key
            description: key of campaign
          - name: campaign_name
            description: name of campaign
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks 
      - name: facebook 
        identifier: raw_gz_facebook
        description: bing marketing campaign
        column:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: facebook
          - name: campaign_key
            description: key of campaign
          - name: campaign_name
            description: name of campaign
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks 
      - name: int_campaigns
        description: data from all campaigns
        tests:
        - unique:
          column_name: "(campaign_key || '-' || date_date)"
        - not_null:
          column_name:
            - paid_source
            - campaign_name
      - name: finance_campaigns_day
        description: global kpi
        columns:
          - name: ads_margin
            description: operational_margin - ads_cost
          - name: average_basket
            description: average basket cost for each day 
            tests:
             - not_null:
               column_name:
                - ads_margin
                - average_basket
     
     
